### ISSUE TITLE
自定义键盘导致其它页面输入框不能输入

### ISSUE THREAD

**Issue by lide1202** [Im-Kevin/cool_ui#10]
自定义键盘只是个别页面，其它普通页面，都是需要文本输入，先在自定义键盘页面触发输入，再转到普通页面，普通页面的输入框，键盘出来，但输入值不会加到textfield

**Comment by Im-Kevin** [comment]
好的,我看看

**Comment by Im-Kevin** [comment]
问题已修复,请更新新的版本0.1.14

**Comment by Im-Kevin** [comment]
如果可以了麻烦关闭一下
