### ISSUE TITLE
只需要部分类拆解的时候找不到某个包

### ISSUE THREAD

**Issue by ddwhan0123** [Im-Kevin/cool_ui#11]
WidgetUtil这类 和ScreenUtil这个 引用哪个包，谢谢

**Comment by Im-Kevin** [comment]
如果你只是想用这两个类,建议你用https://github.com/Sky24n/flustars

**Comment by ddwhan0123** [comment]
好的 谢谢

**Comment by Im-Kevin** [comment]
不建议你拷贝部分代码,Flutter是有tree-shaking优化的,引用整个包对你的打包大小是没有影响的
