### ISSUE TITLE
请问如何设置背景不添加蒙层

### ISSUE THREAD

**Issue by ddwhan0123** [Im-Kevin/cool_ui#12]

**Comment by Im-Kevin** [comment]
你是说Popover吗,目前暂时不支持

**Comment by ddwhan0123** [comment]
Popover cupertino_popover.dart 该文件内修改源码的话能实现么 不需要背景层的话

**Comment by ddwhan0123** [comment]
感谢，在CupertinoPopoverButton这类，62行
修改 barrierColor: Colors.black54, 即可

**Comment by Im-Kevin** [comment]
我已经将barrierColor放出来了,可以设置,不过如果要透明只能设置到Color.fromRGBO(0, 0, 0, 0.01),无法完全透明,请看新的文档
