### ISSUE TITLE
问题：两个使用自定义键盘的 TextField，来回切换键盘会消失，需要重新点击弹出

### ISSUE THREAD

**Issue by ReverseScale** [Im-Kevin/cool_ui#15]
你好啊，非常感谢作者的代码，我在使用中遇到一个问题。

我创建了两个 TextField，当我在一个 TextField 输入完成后，切入第二个 TextField 时，键盘收回了，需要手动再次弹出，不知道有什么方法可以让键盘保持呢

**Comment by ReverseScale** [comment]
我找到方法了：

1.注释 TextInput.clearClient 中对键盘的 hide 和 clear
`
case 'TextInput.clearClient':
          // hideKeyboard(animation: true);
          // clearKeyboard();
          break;
`
2.注释 openKeyboard 中的拦截。
`
static openKeyboard() {
    // if (_keyboardEntry != null) return;
`

**Comment by Im-Kevin** [comment]
这貌似不是最合适的方法,我找时间再看看

**Comment by Im-Kevin** [comment]
我这边无法重现该问题
