### ISSUE TITLE
_debugLifecycleState != _ElementLifecycle.defunct': is not true

### ISSUE THREAD

**Issue by uniquejava** [Im-Kevin/cool_ui#17]
Congrats!  Flutter市集中(pub)唯一能找到的自定义键盘组件.

还没试, 先点赞再使用. 就想问一下. TextFormField 组件中能用吗?

**Comment by Im-Kevin** [comment]
可以的,基于flutter自带的键盘做的,使用方式跟原生键盘一样

**Comment by uniquejava** [comment]
试了没问题， 只是焦点在不同的text field之间切换的过程中。 控制台报下面的错误 ，不影响 使用， 但是看着不舒服。 

@Im-Kevin ， 这是什么错误。 怎样才能解决


I/flutter ( 3827): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3491 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

环境：
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-CN)

**Comment by YMMIOS** [comment]
keyboard_manager里disponse的super写到下面
@override
  void dispose() {
    if(animationController.status == AnimationStatus.forward || animationController.status == AnimationStatus.reverse)
      {
        animationController.notifyStatusListeners(AnimationStatus.dismissed);
      }
    animationController.dispose();
    super.dispose();

  }
