### ISSUE TITLE
Can this plugin work without creating a customised keyboard ?

### ISSUE THREAD

**Issue by MsXam** [Im-Kevin/cool_ui#27]
Im looking into using this KEYBOARD plugin to add a close button to the ON SCREEN KEYBOARD for when focus is made on a textfield. Looking at the example code, from what I can see - there is no way to using the existing keyboard that is shown in iOS or Android ? You have to create your own customised keyboard and register this ? is this correct ? Ideally I just want to overlay the on screen keyboard  with something like an Input Accessory View in iOS which I was hoping this plugin would provide.

**Comment by Im-Kevin** [comment]
Do you mean that you only use a custom keyboard on one platform?

**Comment by MsXam** [comment]
No, hopefully this gif will explain. Here you can see a few textfields. One is made as MultiLine and has an InputAction as Return (Meaning we can add new lines to the textfield) - however , there is no **DONE** button so need to overlay the on screen keyboard with a Close button. Here you can see there is an X to accomplish this. So was wondering if your plugin does the same ?

![closebutton](https://user-images.githubusercontent.com/18722796/63687244-f3a66d80-c7fb-11e9-8aee-6fa9c307213d.gif)

**Comment by Im-Kevin** [comment]
Sorry, my plugin doesn't support this effect, but you can check it out.
Https://pub.dev/packages/keyboard_actions

**Comment by MsXam** [comment]
Thanks - have seen that but there are issues with this. Hopefully the InputAccessoryWidget will arrive soon ...

**Comment by Im-Kevin** [comment]
You can consider writing a copy yourself with Stack.
MediaQueryData.viewInsets.bottom is the height of the keyboard
