### ISSUE TITLE
您好，我下载了您的示例，进入自定义键盘的页面，获取焦点后，返回主页面时出现了异常

### ISSUE THREAD

**Issue by kmarryme** [Im-Kevin/cool_ui#32]
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by Im-Kevin** [comment]
好的,我看看

**Comment by Im-Kevin** [comment]
问题已经修复
