### ISSUE TITLE
一个页面不同自定义键盘来回切换有问题

### ISSUE THREAD

**Issue by shuigesuntao** [Im-Kevin/cool_ui#36]
一个页面两个TextField 2个自定义键盘 高度不同 切换焦点时 会按照上个自定义键盘高度计算高度 导致显示不全或超出

**Comment by Im-Kevin** [comment]
已修复,升级版本0.3.3

**Comment by shuigesuntao** [comment]
丛高变低没问题 但是从低变高依然有问题

**Comment by Im-Kevin** [comment]
已修复,升级版本0.4.0,有参数改变,请注意
