### ISSUE TITLE
 pub.dev上的0.4.1和github上的代码没同步

### ISSUE THREAD

**Issue by gongqinjing** [Im-Kevin/cool_ui#37]
导致有两个键盘切换的时候有一系列报错，github上的代码没有问题

**Comment by Im-Kevin** [comment]
请贴一下具体报错信息

**Comment by gongqinjing** [comment]
═══════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): KeyboardPageState#836dd(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1112
#1      State.setState 
package:flutter/…/widgets/framework.dart:1147
#2      KeyboardPageState.updateHeight.<anonymous closure> 
package:cool_ui/keyboards/keyboard_manager.dart:424
#3      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
#4      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1049
...
═══════════════════════════════════════════════
用的代码是example ，没有改动

**Comment by FlutterDevelopers** [comment]
遇到同样的问题，什么时候能同步pub.dev上的0.4.1与github上的代码？

**Comment by liuyangliuyang** [comment]
遇到同样的问题，什么时候能把pub.dev上的0.4.1和github上的代码同步？

**Comment by Im-Kevin** [comment]
请查看最新版本
