### ISSUE TITLE
androidx 使用cool_ui遇到的问题

### ISSUE THREAD

**Issue by chenjuyu** [Im-Kevin/cool_ui#38]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, No such TextInputType: CKNumberKeyboard, null)
使用example中的CustomKeyboardDemo dart文件 焦点到输入框，提示如上错误，弹出键盘没有控制到只显示数字，
环境：D:\my_app\my_app>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.864], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\IDEA20193
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • MOGOLIA • F2C7N15429014716 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 1 category.

**Comment by Im-Kevin** [comment]
你用的是哪个版本

**Comment by chenjuyu** [comment]
3.1与4.1都试过了，都出现这个问题，没见弹出数字键盘




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年2月6日(星期四) 晚上6:57
收件人: "Im-Kevin/cool_ui"<cool_ui@noreply.github.com&gt;; 
抄送: "CHEN"<2498525982@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Im-Kevin/cool_ui] androidx 使用cool_ui遇到的问题 (#38)




你用的是哪个版本

**Comment by Im-Kevin** [comment]
你是直接运行Demo吗,还是有所改动

**Comment by Im-Kevin** [comment]
如果只是把CustomKeyboardDemo 搬过去,则需要把这几步做一下
![image](https://user-images.githubusercontent.com/15227529/74081876-a575e580-4a8e-11ea-8ed4-881f5a730d49.png)

**Comment by Im-Kevin** [comment]
具体你可以看这个[自定义键盘使用方法快速入门](https://github.com/Im-Kevin/cool_ui/blob/master/documents/custom_keyboard.md)

**Comment by chenjuyu** [comment]
> 具体你可以看这个[自定义键盘使用方法快速入门](https://github.com/Im-Kevin/cool_ui/blob/master/documents/custom_keyboard.md)

谢谢，可以了，但是使用你自带的demo，输入框，来回切换还是会把这个错误
Unhandled Exception: PlatformException(error, No such TextInputType: CKTestKeyboard, null)
先切到输入数字键盘的，然后焦点放到多键盘的文本框，再切回数字键盘还是会报这个为null

**Comment by Im-Kevin** [comment]
好的,我修正一下Demo

**Comment by chenjuyu** [comment]
> 好的,我修正一下Demo
还有一个问题，就是下载其他github上的库存 时，重新flutter pub get 就会报如下错误，然后我是先把依赖版本改为0.3.1后重新get，然后又改为0.4.1 后 get 才正常，大佬有遇到过吗？
Because no versions of cool_ui match 0.4.1 and no versions of cool_ui match >0.4.1 <0.5.0, cool_ui ^0.4.1 is forbidden.
So, because my_app depends on cool_ui ^0.4.1, version solving failed.

**Comment by Im-Kevin** [comment]
你可以试着删掉pubspec.lock再重新执行看看,这个可能是镜像的一些Bug

**Comment by lumia1999** [comment]
static const CKTextInputType inputType =
      const CKTextInputType(name: 'GameNumberKeyboard'); //定义InputType类型

 Unhandled Exception: PlatformException(error, No such TextInputType: GameNumberKeyboard, null)


为什么总是报错？
