### ISSUE TITLE
popoverColor does not work only colors the triangle

### ISSUE THREAD

**Issue by shamilovtim** [Im-Kevin/cool_ui#40]
<img width="226" alt="Screen Shot 2020-03-23 at 7 26 05 PM" src="https://user-images.githubusercontent.com/3495974/77372553-3f8ea600-6d3c-11ea-8684-95386c255a02.png">
<img width="238" alt="Screen Shot 2020-03-23 at 7 26 12 PM" src="https://user-images.githubusercontent.com/3495974/77372555-41586980-6d3c-11ea-806d-504ccedaa5bf.png">

**Comment by Im-Kevin** [comment]
0.5.5 Fix Bug
