### ISSUE TITLE
如何避免重复弹出

### ISSUE THREAD

**Issue by zinwalin** [Im-Kevin/cool_ui#46]
或者说怎么判断是不是已经弹出？

**Comment by Im-Kevin** [comment]
你是怎么出现重复弹出的

**Comment by zinwalin** [comment]
> 你是怎么出现重复弹出的

多个图片或视频上传中，有些视频未上传完成时，点击发送，这时显示'上传中，请稍等'，等视频上传完成后回调完成发送。回调前，showWeuiLoadingToast界面一直要转圈圈，需不需要回调以showWeuiLoadingToast界面是否存在为条件。

**Comment by Im-Kevin** [comment]
showWeuiLoadingToast 会返回一个方法,你应该保存下来,然后通过判断这个是否为null, 执行后应该把他设置为null
