### ISSUE TITLE
Normal keyboard 

### ISSUE THREAD

**Issue by klaszlo8207** [Im-Kevin/cool_ui#49]
How can I create a normal keyboard not the Numeric one?

I need basically the default android one without emojis, microfon, and others

So:

A-z 0-9 and special chars (and accents)

like here:

https://images.techhive.com/images/article/2014/12/android_typing_tips_accent-100538029-orig.jpg

it is enough to set "a", and "á", or "e" or "é"

thanks

**Comment by Im-Kevin** [comment]
I just provide a tool. You can make it according to your needs

**Comment by klaszlo8207** [comment]
Thanks, I just created it now. Very good lib :)

Better then the default keyboard, because that is always rebuilds the widget tree

Thanks!!!
