### ISSUE TITLE
8月5日iOS运行的时候报错了，之前都不会是不是依赖的back_button_interceptor更新了，keyboard没有适配呀？

### ISSUE THREAD

**Issue by cxycwz** [Im-Kevin/cool_ui#55]
/Users/avalanching/iOS_word/ios_app/../../flutter_work/flutter_module/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

Compiler message:
../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/cool_ui-0.6.0/lib/dialogs/weui_toast.dart:207:29: Error: The argument type 'bool Function(bool)' can't be assigned to the parameter type 'bool Function(bool, RouteInfo)'.
 - 'RouteInfo' is from 'package:back_button_interceptor/src/back_button_interceptor.dart' ('../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/back_button_interceptor-4.3.0/lib/src/back_button_interceptor.dart').
  BackButtonInterceptor.add((stopDefaultButtonEvent){
                            ^
../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/cool_ui-0.6.0/lib/keyboards/keyboard_manager.dart:170:31: Error: The argument type 'bool Function(bool)' can't be assigned to the parameter type 'bool Function(bool, RouteInfo)'.
 - 'RouteInfo' is from 'package:back_button_interceptor/src/back_button_interceptor.dart' ('../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/back_button_interceptor-4.3.0/lib/src/back_button_interceptor.dart').
    BackButtonInterceptor.add((_) {
                              ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by Im-Kevin** [comment]
请使用新版本

**Comment by roychenggit** [comment]
../../.pub-cache/hosted/pub.flutter-io.cn/cool_ui-0.6.3/lib/keyboards/keyboard_manager.dart:24:10: Context: Found this candidate, but the arguments don't match.
  static init(KeyboardRootState root, BuildContext context) {
