### ISSUE TITLE
unfocus之后keyboard_manager.dart中的hideKeyboard异常

### ISSUE THREAD

**Issue by wzw-gh** [Im-Kevin/cool_ui#56]
if (animation) {
        _pageKey.currentState.exitKeyboard();                --focusnode调用unfocus之后_pageKey.currentState为null
        Future.delayed(Duration(milliseconds: 116)).then((_) {
          _root.clearKeyboard();
        });
      } else {
        _root.clearKeyboard();
      }

**Comment by Im-Kevin** [comment]
你是什么版本

**Comment by Im-Kevin** [comment]
许久未回复
