### ISSUE TITLE
只需要抬起textfield的效果，该怎么做？

### ISSUE THREAD

**Issue by yeyicheng** [Im-Kevin/cool_ui#59]
您好，
我现在不需要自定义键盘，只想要点击textfield可以抬起输入框。
该怎么做？

我现在在Scaffold外面添加了KeyboardMediaQuery，但是没有反应...

谢谢

**Comment by Im-Kevin** [comment]
KeyboardMediaQuery这个是配合自定义键盘使用的,像你这种应该在输入框外面添加ListView这些有滚动效果的控件
