### ISSUE TITLE
Toast不居中

### ISSUE THREAD

**Issue by YaoShuwei** [Im-Kevin/cool_ui#6]
![screenshot_2018-11-10-22-51-13-005_com yufeinong](https://user-images.githubusercontent.com/17966298/48302845-f2da6e80-e53c-11e8-9a99-2526f12f8a64.png)

**Comment by Im-Kevin** [comment]
这个不居中我是参照Weui的,或许因为是固定值的原因,所以看起来可能不好看,我之后会用相对布局,并且可以自定义

**Comment by Im-Kevin** [comment]
已经更新了版本,添加了alignment,不过我建议你先看看改后的版本,我目前还是不是完全居中的,你如果觉得需要居中,可以自己去设置,具体看0.1.6版本

**Comment by YaoShuwei** [comment]
谢谢，刚才看到了Alignment，我还以为是我之前眼瞎了呢。我现在去试试看
