### ISSUE TITLE
调用 CoolKeyboard.updateKeyboardHeight()不起作用

### ISSUE THREAD

**Issue by weiwill** [Im-Kevin/cool_ui#65]
希望能改成这样
`// _pageKey!.currentState!.updateHeight(_keyboardHeightNotifier.value); _pageKey!.currentState!.updateHeight(_currentKeyboard!.getHeight(_context!));`

**Comment by Im-Kevin** [comment]
意图在哪,这个东西目前由我这边内部自行更新的

**Comment by weiwill** [comment]
需要做类似中英文切换，切换后键盘高度会改变，所以需要更新键盘高度

**Comment by Im-Kevin** [comment]
这种建议你写两个键盘

**Comment by Im-Kevin** [comment]
通过TextInputType切换键盘

**Comment by weiwill** [comment]
也是一种思路吧，不过这样切换键盘，键盘应该会收起重新弹出，效果不是很好

**Comment by Im-Kevin** [comment]
不会的,我这边是做了优化,你可以试试,切换成原生键盘是会有这种影响,因为原生键盘无法控制,自定义键盘之间切换不会重新弹出
