### ISSUE TITLE
setMockMessageHandler Issue

### ISSUE THREAD

**Issue by zohaib012345** [Im-Kevin/cool_ui#70]
Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
![flutter issue](https://user-images.githubusercontent.com/53237092/132846837-a3bfd6ae-2e42-42f1-b60f-f349f363dbe2.PNG)

**Comment by Im-Kevin** [comment]
Please use cool_ui 1.1.0

**Comment by Im-Kevin** [comment]
Please replace runApp with runMockApp
Please see the documentation for details
