### ISSUE TITLE
Exception: CoolKeyboard can only be used in MockBinding

### ISSUE THREAD

**Issue by l000in** [Im-Kevin/cool_ui#74]
flutter 2.5.1 ,cool_ui 1.1.0 ,

**Comment by l000in** [comment]
![image](https://user-images.githubusercontent.com/91250846/134476728-efab2cf6-a98c-4793-9a68-0f3fb5302f5c.png)

**Comment by Im-Kevin** [comment]
请把main方法的代码贴全面一点

**Comment by l000in** [comment]
![image](https://user-images.githubusercontent.com/91250846/134477246-6e3bd337-dc1d-46db-9958-827c9bcc56b4.png)

**Comment by Im-Kevin** [comment]
请把WidgetsFlutterBinding.ensureInitialized()改成
MockBinding.ensureInitialized()

**Comment by l000in** [comment]
改了就可以了，谢谢

**Comment by Im-Kevin** [comment]
不用谢
