### ISSUE TITLE
自定义键盘报错求解决

### ISSUE THREAD

**Issue by JasonWang93** [Im-Kevin/cool_ui#79]
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, No such TextInputType: CKDeviceRecordKeyboard, null, null)

**Comment by Im-Kevin** [comment]
有相关代码吗,我看这个是你自己定义的一个Keyboard

**Comment by Dabbit-Chan** [comment]
> 有相关代码吗,我看这个是你自己定义的一个Keyboard

flutter版本2.2.3

main.dart

void main() {
  MyKeyboard.register();
  NumberKeyboard.register();
  runApp(MyApp());
}

custom_keyboard_page.dart

Widget build(BuildContext context) {
    return KeyboardMediaQuery(
      child: Builder(
        builder: (context) {
          return Scaffold(
              appBar: AppBar(title: Text('Custom Keyboard Page')),
              body: SingleChildScrollView(
                child: Column(
                  children: [
                    TextField(
                      // keyboardType: MyKeyboard.inputType,
                      keyboardType: NumberKeyboard.inputType,
                    ),
                  ],
                ),
              ));
        },
      ),
    );
  }

报错
E/MethodChannel#flutter/textinput(11298): Failed to handle method call
E/MethodChannel#flutter/textinput(11298): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:449)
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:138)
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(11298): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(11298): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(11298): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput(11298): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput(11298): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput(11298): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(11298): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput(11298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (11298): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, No such TextInputType: CKNumberKeyboard, null, null)
E/flutter (11298): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter (11298): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (11298): <asynchronous suspension>
E/flutter (11298): 
E/flutter (11298): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
E/flutter (11298): 	at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:449)
E/flutter (11298): 	at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:138)
E/flutter (11298): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter (11298): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (11298): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (11298): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (11298): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11298): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (11298): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (11298): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (11298): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11298): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (11298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (11298): )
E/flutter (11298): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
E/flutter (11298): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (11298): <asynchronous suspension>
E/flutter (11298):

**Comment by Im-Kevin** [comment]
键盘部分的代码,还有这个键盘有没有注册

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/161186733-fdd6f5c9-c841-471f-b304-f1387d38a3a1.png)

**Comment by Im-Kevin** [comment]
@Dabbit-Chan

**Comment by Dabbit-Chan** [comment]
我这里用的是你写的那个number_keyboard.dart，不是自己写得那个

**Comment by Im-Kevin** [comment]
有用这个吗
![image](https://user-images.githubusercontent.com/15227529/161187508-7b87d4cd-a0e1-443a-b1c9-05a70118bf2b.png)

**Comment by Im-Kevin** [comment]
需要最外面添加RootWidget

**Comment by Dabbit-Chan** [comment]
> 有用这个吗 ![image](https://user-images.githubusercontent.com/15227529/161187508-7b87d4cd-a0e1-443a-b1c9-05a70118bf2b.png)

ok了，感谢感谢，忘记配KeyboardRootWidget了

**Comment by Im-Kevin** [comment]
不用谢
