### ISSUE TITLE
自定义键盘好像自身没有高度

### ISSUE THREAD

**Issue by 309791679** [Im-Kevin/cool_ui#83]
`showModalBottomSheet(
                                    isScrollControlled: true,
                                    builder: (BuildContext context) {
                                      //构建弹框中的内容
                                      return Container(
                                          margin: EdgeInsets.only(bottom:MediaQuery.of(context).viewInsets.bottom), //这个段代码，实现这个底部跟随
                                          width: 300.r,
                                          height: 220.r,
                                          decoration: BoxDecoration(
                                              borderRadius: BorderRadius.only(topLeft: Radius.circular(10.r),topRight: Radius.circular(10.r)),
                                              //color: Color.fromRGBO(249, 249, 249, 1)
                                              color: Colors.white
                                          ),`
//现在是正常的键盘可以让showModalBottomSheet容器底部跟随键盘高度，但是自定义键盘就不行，我的测试是它没有高度

**Comment by 309791679** [comment]
我的代码
class NumberKeyboar extends StatelessWidget{
  static const CKTextInputType inputType1 = const CKTextInputType(name:'CKNumberKeyboard');
  static double getHeight(BuildContext ctx){
    MediaQueryData mediaQuery = MediaQuery.of(ctx);
    return 365.r; //355.r
    //return mediaQuery.size.width / 3 / 2 * 2;
  }
  final KeyboardController? controller ;
  const NumberKeyboar({this.controller});

  static register(){
    CoolKeyboard.addKeyboard(NumberKeyboar.inputType1,KeyboardConfig(builder: (context,controller, params){
      return NumberKeyboar(controller: controller);
    },getHeight: NumberKeyboar.getHeight));
  }


  @override
  Widget build(BuildContext context) {
    MediaQueryData mediaQuery = MediaQuery.of(context);
    return Container(
      width: 414.r,
      height: 365.r,

      //padding: EdgeInsets.only(top:21.5.r),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.only(topLeft: Radius.circular(20.r),topRight: Radius.circular(20.r)),
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.06),
            spreadRadius: 3.r,
            blurRadius: 2,
            offset: Offset(1, 0),
          ),
        ],

      ),


      child: Stack(
        children: [
          Positioned(
            bottom: 0,
            child: 
          ),
        ],



      ),
    );
  }

  Widget buildButton(String title,{required String value}){
    return Container(
      color: Colors.white,
      child: GestureDetector(
        behavior: HitTestBehavior.translucent,
        child: Center(child: Text(title),),
        onTap: (){
          controller?.addText(value);
        },
      ),
    );
  }
}

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/183322612-b0bd50d9-2629-4802-939c-dbf635cc3e5a.png)
这个没有加

**Comment by 309791679** [comment]
> ![image](https://user-images.githubusercontent.com/15227529/183322612-b0bd50d9-2629-4802-939c-dbf635cc3e5a.png) 这个没有加

是的，官方例子是Navigator跳转后才能在输入框有焦点是滚动，直接调用输入框获取焦点时并不会滚动而是在输入时激活滚动，按照我的写法就没有这个问题了


`void main() async {
  NumberKeyboar.register();
  runMockApp(KeyboardRootWidget(child: MyApp())); // 新的
  await ScreenUtil.ensureScreenSize();
}

class MyApp extends StatelessWidget {
  MyApp() {
    BaseRouter.setRouter(FluroRouter());
    BaseRouter.registerConfigureRoutes(BaseRouter.getRouter());
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate, // 指定本地化的字符串
        GlobalCupertinoLocalizations.delegate, // 对应的Cupertino风格
        GlobalWidgetsLocalizations.delegate // 指定默认的文本排列方向, 由左到右或由右到左
      ],
      supportedLocales: [Locale("en"), Locale("zh")],
      debugShowCheckedModeBanner: false,
      onGenerateRoute: BaseRouter.getRouter().generator,
      builder: (ctx, child) {
        ScreenUtil.init(ctx,designSize:Size(414,736));
        return Theme(
          data: ThemeData(),
          child: Navigator(
            onGenerateRoute: (_) => MaterialPageRoute(
              builder: (ctx) => LoginPage(),
            ),
          ),
        );
      },
    );
  }
}
LoginPage 这边的结构
Widget build(BuildContext context) {


    return  KeyboardMediaQuery(
      child: Scaffold())
}

`

**Comment by 309791679** [comment]
LoginPage 这边的结构

`Widget build（BuildContext context） {

return  KeyboardMediaQuery(
  child: Scaffold())
}`

**Comment by 309791679** [comment]
![image](https://user-images.githubusercontent.com/26238458/183402163-032a2260-c849-404a-a4d6-0ad5b131b03a.png)

**Comment by 309791679** [comment]
返回直接退出 使用这个

home: Builder(builder: (BuildContext context) {
        ScreenUtil.init(context,designSize:Size(414,690));
        return LoginPage();
      },),

**Comment by Im-Kevin** [comment]
不是很理解你在说什么,有点散

**Comment by 309791679** [comment]
> 不是很理解你在说什么,有点散

大概就是，获取不到输入法的高度
