### ISSUE TITLE
bug Issues : update flutter v3.3.0 , custom keyboard not work...

### ISSUE THREAD

**Issue by lihehehehe** [Im-Kevin/cool_ui#86]
update flutter v3.3.0  , custom keyboard not work
update flutter v3.3.0  , custom keyboard not work
update flutter v3.3.0  , custom keyboard not work

please fix as soon as possible.

**Comment by Shawnli1201** [comment]
flutter v3.3, 为了解决这个问题https://github.com/flutter/flutter/pull/101087,将TextInput初始化时间提前了，着急的话，可以先在Flutter SDK中注释掉TextInput.ensureInitialized();  可以正常使用。

**Comment by lihehehehe** [comment]
> flutter v3.3, 为了解决这个问题[flutter/flutter#101087](https://github.com/flutter/flutter/pull/101087), 将TextInput初始化时间提前了，着急的话，可以先在Flutter SDK中注释掉TextInput.ensureInitialized(); 可以正常使用。

1

**Comment by Im-Kevin** [comment]
已上传1.3版本
