### ISSUE TITLE
CupertinoPopoverMenuItem 能否可以自定义颜色大小等？

### ISSUE THREAD

**Issue by yimity** [Im-Kevin/cool_ui#9]
CupertinoPopoverMenuItem 能否可以自定义 icon 和 文字的颜色大小等？

**Comment by Im-Kevin** [comment]
icon 和文字都是一个widget 来的,我只是提供了默认样式,你可以去给你自己的widget设置样式

**Comment by yimity** [comment]
@Im-Kevin 哦哦哦，是我看错了，不好意思。
